### ISSUE TITLE
Cannot GET /1.jpg

### ISSUE THREAD

**Issue by Luporion** [jeffmikels/vmix-snapshot-proxy#1]
When trying to recieve a snapshot of input 1 i get the following error:

Cannot GET /1.jpg

same for all other inputs; the app isn't showing neither error or picture. Am i missing somthing?

git bash output:

/1.jpg
http://localhost:8088/api?Function=SnapshotInput&Input=1&Value=1.jpg
/2.jpg
http://localhost:8088/api?Function=SnapshotInput&Input=2&Value=2.jpg
Function completed successfully.
Function completed successfully.

**Comment by jeffmikels** [comment]
I am now releasing a totally different binary version based on Go instead of JavaScript.
