### ISSUE TITLE
Error after "node index.js"

### ISSUE THREAD

**Issue by topherharris** [jeffmikels/vmix-snapshot-proxy#3]
I get this result when running "node index.js" (after editing top of index.js)

$ node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'got'
Require stack:
- C:\Users\ristophe\vmix-snapshot-proxy\index.js
?[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:9
33:15)?[39m
?[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)?[39m

?[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)?[39m
?[90m    at require (node:internal/modules/cjs/helpers:102:18)?[39m
    at Object.<anonymous> (C:\Users\ristophe\vmix-snapshot-proxy\index.js:13:13)

?[90m    at Module._compile (node:internal/modules/cjs/loader:1103:14)?[39m
?[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157
:10)?[39m
?[90m    at Module.load (node:internal/modules/cjs/loader:981:32)?[39m
?[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)?[39m

?[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/r
un_main:77:12)?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: [ ?[32m'C:\\Users\\ristophe\\vmix-snapshot-proxy\\index.js'?[39m
 ]
}

**Comment by jeffmikels** [comment]
I'm now releasing a different version entirely based on Go.
